### ISSUE TITLE
Unnecessary traversal

### ISSUE THREAD

**Issue by matkoch** [kthompson/glob#20]
I've noticed that this library traverses more than necessary. For instance in an environment with:

```
Root
+ A
+ B
  - B.1
  - B.2
+ C
```

It even traverses `A` and `C` despite my pattern being `B\B.*`. This is far beyond usefulness in bigger folder structures. 

Code in question is here: `glob/src/Glob/GlobExtensions.cs`

**Comment by kthompson** [comment]
I think i see what you mean currently there is no support for partial
matching which I think would be necessary in order to only traverse
directory's that match. Which means we would need to move away from the
regex converter. If you'd like to submit a PR or have any additional
thoughts I'd be happy to look at them.

**Comment by kthompson** [comment]
Minor update on this, but just wanted to note that the back end now uses internal AST that can now be used to do traversal of paths more efficiently. Still some work to be done though.
