### ISSUE TITLE
( ) and = cannot be escaped

### ISSUE THREAD

**Issue by jesong** [kthompson/glob#57]
error calling
```
 var match = Glob.IsMatch(@"a\abc(v=ws.10).md", @"a\abc\(v\=ws.10\).md", GlobOptions.CaseInsensitive);
```

```
System.Exception: 'Unable to scan for next token. Stuck on '(''
```

**Comment by kthompson** [comment]
@jesong I just made a release that should allow for parens and nearly all characters except for characters that are special for parsing globs. ie *?![]{,}/\ Which I will address in issue #41 once escaping glob characters are supported.

**Comment by jesong** [comment]
Thank you for the quick fix. I'll try out.

**Comment by jesong** [comment]
Sorry this is not work as expected
```
 bool isMatch = Glob.IsMatch(@"a\abc(v=ws.10).md", @"a\abc\(v\=ws.10\).md", GlobOptions.CaseInsensitive);
```
now will not throw exception. But the "isMatch" result is false.

**Comment by kthompson** [comment]
I believe in the example of bash, bash itself has special meaning for `(` or `)` which is why the escape in the shell is required. Currently they have no special meaning in the supported features of this library. It support for extended glob expressions is ever desired then I will probably need to revisit this.

Thanks
